//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TinyUML.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDR_MAINFRAME                   128
#define IDR_TINYUMTYPE                  129
#define IDB_TTF_BMP                     129
#define IDR_CONTEXT_MENU                130
#define IDR_POPUP_TOOLBAR               131
#define IDR_TOOLSBAR                    141
#define IDR_DRAW_TOOLBAR                141
#define IDR_VIEWBAR                     144
#define IDB_WORKSPACE                   147
#define IDR_OBJECTBAR                   148
#define IDD_PROP_NOTE                   152
#define IDD_PROP_PACKAGE                153
#define IDB_CLASS                       154
#define IDD_PROP_DEPENDENCY             154
#define IDB_PROJECT                     155
#define IDD_PROP_GENERALIZATION         155
#define IDD_PROP_ASSOCIATION            156
#define IDB_PUBLIC_METHOD               156
#define IDB_PRIVATE_METHOD              157
#define IDD_PROP_CLASS                  158
#define IDB_PROTECTED_METHOD            158
#define IDD_PROP_METHODS                159
#define IDB_PUBLIC_MEMBER               159
#define IDD_PROP_ATTRIBUTES             160
#define IDB_PROTECTED_MEMBER            160
#define IDB_PRIVATE_MEMBER              161
#define IDR_CLASS_EDITOR                163
#define IDR_UML_TOOLBAR                 164
#define IDR_STYLE_TOOLBAR               165
#define IDB_CLASS_EDITOR                169
#define IDD_CLASS_EDITOR                170
#define IDI_REMOVE                      172
#define IDI_ADD                         173
#define IDI_SET                         174
#define IDD_PROP_CLASS_THEME            178
#define IDB_THEME                       179
#define IDD_PROP_NOTE_THEME             180
#define IDD_PROP_RELATION_THEME         181
#define IDD_PROP_PACKAGE_THEME          182
#define IDD_PROP_GENERAL_THEME          183
#define IDD_EDIT_METHOD_CODE            185
#define IDD_WRITE_SOURCES               186
#define IDI_OPEN                        187
#define IDI_EDIT_METHOD                 188
#define IDR_FILEVIEW_CONTEXT_MENU       192
#define IDD_PROP_LABEL                  193
#define IDC_MOUSE_CURSOR                194
#define IDI_CANCEL                      202
#define IDI_OK                          210
#define IDD_NO_TOOL                     245
#define IDC_TEXT                        1000
#define IDC_NAME                        1001
#define IDC_SHOW_ARROW                  1002
#define IDC_REALIZE                     1003
#define IDC_SOURCE_MULTIPLICITY         1005
#define IDC_DEST_MULTIPLICITY           1006
#define IDC_SHOW_SRC_MULTIPLICITY       1007
#define IDC_SHOW_DEST_MULTIPLICITY      1008
#define IDC_AGGREGATION                 1009
#define IDC_NAVIGABLE                   1010
#define IDC_SHOW_NAME                   1012
#define IDC_STEREOTYPE                  1014
#define IDC_SHOW_STEREOTYPE             1015
#define IDC_ABSTRACT_CLASS              1016
#define IDC_SHOW_COMPARTIMENTS_NAME     1017
#define IDC_SHOW_ATTRIBUTES             1018
#define IDC_REMOVE_ATTRIBUTE            1020
#define IDC_ADD_ATTRIBUTE               1021
#define IDC_MOVE_ATTRIBUTE              1022
#define IDC_ATTRIBUTE_NAME              1023
#define IDC_ATTRIBUTE_TYPE              1024
#define IDC_SHOW_METHODS                1025
#define IDC_SET_ATTRIBUTE               1025
#define IDC_METHODS                     1026
#define IDC_ADD_METHOD                  1027
#define IDC_REMOVE_METHOD               1028
#define IDC_MOVE_METHOD                 1029
#define IDC_METHOD_NAME                 1030
#define IDC_METHOD_ACCESS               1031
#define IDC_METHOD_TYPE                 1032
#define IDC_SET_METHOD                  1033
#define IDC_EDIT_METHOD                 1034
#define IDC_COMPANY_URL                 1041
#define IDC_MEMBER_ACCESS               1042
#define IDC_EDIT_NOTE                   1043
#define IDC_EDIT_INITIAL_VALUE          1044
#define IDC_ATTRIBUTES                  1045
#define IDC_EDIT1                       1046
#define IDC_CHECK_STATIC                1047
#define IDC_EDIT_ATTRIBUTE_FONT_SIZE    1047
#define IDC_LIST_METHOD                 1048
#define IDC_EDIT_METHOD_FONT_SIZE       1048
#define IDC_BUTTON_CLASS_TITLE_COLOR    1051
#define IDC_BUTTON_CLASS_BACK_COLOR     1052
#define IDC_COMBO_NAME_FONT             1053
#define IDC_COMBO_ATTRIBUTE_FONT        1054
#define IDC_SPIN_ATTRIBUTE_FONT_SIZE    1055
#define IDC_COMBO_METHOD_FONT           1056
#define IDC_SPIN_METHOD_FONT_SIZE       1057
#define IDC_SPIN_NAME_FONT_SIZE         1058
#define IDC_EDIT_NAME_FONT_SIZE         1059
#define IDC_BUTTON_NAME_COLOR           1060
#define IDC_BUTTON_FOLDER_COLOR         1061
#define IDC_BUTTON_ATTRIBUTE_COLOR      1062
#define IDC_BUTTON_METHOD_COLOR         1063
#define IDC_BUTTON_NOTE_COLOR           1064
#define IDC_COMBO_NOTE_FONT             1065
#define IDC_CONSTMETHOD                 1066
#define IDC_BUTTON_SYMBOL_COLOR         1066
#define IDC_BUTTON_FILL_COLOR           1067
#define IDC_VIRTUAL                     1068
#define IDC_BUTTON_LINE_COLOR           1068
#define IDC_PURE                        1069
#define IDC_BUTTON_SHADOW_COLOR         1069
#define IDC_EDIT_METHOD_CODE            1069
#define IDC_EDIT_NAME                   1070
#define IDC_EDIT_BEGIN                  1071
#define IDC_EDIT_END                    1072
#define IDC_BUTTON_CLOSE                1073
#define IDC_BUTTON_SAVE                 1074
#define IDC_INLINE                      1075
#define IDC_LIST_FILES                  1075
#define IDC_EDIT_REPOSITORY             1076
#define IDC_EDIT_COMMENTS               1077
#define IDC_BUTTON_SELECT_REPOSITORY    1078
#define IDC_STATIC_METHOD               1080
#define IDC_FRAME                       1081
#define IDC_UMLSCULPTOR_URL             1082
#define IDC_LABEL                       1083
#define IDC_DLLEXPORT                   1109
#define IDC_SINGLETON                   1110
#define IDC_CALLINGCONVENTION           1215
#define IDC_IMPLEMENT                   1219
#define IDC_DECLARE                     1220
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_TOOL_SELECT                  32771
#define ID_TOOL_CLASS                   32772
#define ID_TOOL_NOTE                    32773
#define ID_TOOL_GENERALIZATION          32774
#define ID_TOOL_ASSOCIATION3            32775
#define ID_TOOL_DEPENDENCY              32776
#define ID_VIEWMIN                      32777
#define ID_VIEWNORMAL                   32778
#define ID_VIEWMAX                      32779
#define ID_VIEWGRID                     32780
#define ID_VIEW_LOCK                    32781
#define ID_BUTTON32782                  32782
#define ID_BUTTON32783                  32783
#define ID_BUTTON32786                  32786
#define ID_BUTTON32787                  32787
#define ID_TOOL_PACKAGE                 32788
#define ID_TOOL_INTERFACE               32792
#define ID_TOOL_ASSOCIATION1            32793
#define ID_TOOL_ASSOCIATION2            32794
#define ID_TOOL_REALIZE                 32795
#define ID_SCALE_COMBO                  32802
#define ID_VIEW_WORKSPACE               32803
#define ID_VIEW_OUTPUT                  32804
#define ID_DRAWING_LINE_COLOR           32805
#define ID_UNDO                         32822
#define ID_REDO                         32823
#define ID_VIEW_TOOLSBAR                32824
#define ID_EDIT_PROPERTIES              32825
#define ID_FILE_SAVESOURCE              32828
#define ID_FILE_READSOURCE              32829
#define ID_ARRANGE_SEND_TO_BACK         32830
#define ID_ARRANGE_BRING_TO_FRONT       32831
#define ID_TOOL_IMAGE                   32840
#define ID_CLASS_EDIT_PASTE             32845
#define ID_CLASS_EDIT_FIND              32846
#define ID_CLASS_EDIT_REPLACE           32847
#define ID_CLASS_EDIT_COPY              32848
#define ID_CLASS_EDIT_CUT               32849
#define ID_EDIT_CLASS                   32850
#define ID_SAVE_THEME                   32851
#define ID_LOAD_THEME                   32852
#define ID_UML_SETTING                  32853
#define ID_INSERT_IMAGE                 32854
#define ID_TOOL_LABEL                   32855
#define ID_FILE_PURGE                   32856
#define ID_EDIT_GROUP                   32857
#define ID_EDIT_UNGROUP                 32858
#define ID_INSERT_CLASS                 32859
#define ID_FILE_ADD_TO_DOCUMENT         32860
#define ID_DRAW_TOOL_LINE               32861
#define ID_DRAW_TOOL_RECT               32862
#define ID_DRAW_TOOL_ELLIPSE            32863
#define ID_DRAW_TOOL_ARC                32864
#define ID_DRAW_TOOL_BEZIER             32865
#define ID_DRAW_TOOL_IMAGE              32866
#define ID_DRAWING_LINE_STYLE           32867
#define ID_DRAWING_LINE_WEIGHT          32868
#define ID_INDICATOR_DATE               59142
#define ID_INDICATOR_TIME               59143
#define ID_INDICATOR_MOUSEPOS           59144
#define ID_INDICATOR_SNAP               59145
#define IDS_FILE_OUTDATED_WARNING       61216
#define IDS_FILE_TOO_NEW_ERROR          61217
#define IDS_SOURCE_GENERALIZATION_ERROR 61218
#define IDS_DESTINATION_GENERALIZATION_ERROR 61219
#define IDS_SOURCE_AGGREGATION_ERROR    61220
#define IDS_DEST_SRC_GENERALIZATION_ERROR 61221
#define IDS_50PERCENT                   61446
#define IDS_100PERCENT                  61447
#define IDS_150PERCENT                  61448
#define IDS_200PERCENT                  61449
#define IDS_500PERCENT                  61450
#define IDS_DEFAULT_FONT                61451
#define IDS_25PERCENT                   61452
#define IDS_BAD_PERCENT                 61453
#define ID_NEW_CLASS                    61454
#define ID_EDIT_THEME                   61455
#define IDS_FILE_VIEW_STRING1           61456
#define IDS_FILE_VIEW_STRING2           61457
#define IDS_FILE_VIEW_STRING3           61458
#define IDS_FILE_VIEW_STRING4           61459

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         32869
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
